# Generated by Django 6.0.4 on 2026-04-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
