# Generated by Django 6.0.4 on 2026-04-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0003_slot_remove_booking_date_remove_booking_is_booked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
